### ISSUE TITLE
No GPU being used. (NVIDIA)

### ISSUE THREAD

**Issue by pupdike** [rsxdalv/tts-generation-webui#55]
When I launch I get this message:
```
No GPU being used. Careful, inference might be very slow!
```
I also get this message earlier in the log, though I am not sure it is related:
```
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
```

I indicated option "A" when I installed but it didn't seem to get my 4090 GPU. Should I try reinstalling, or is there any quicker way to try to repair the GPU detection issue?

**Comment by rsxdalv** [comment]
That's a bigger problem, could you please post your system information? I
believe you did in the other thread but I'm not sure.
And did you select Nvidia when running the installer?

**Comment by pupdike** [comment]
I am running on Windows 11 with and NVIDIA 4090 series GPU. I believe I selected "A" for the graphics card which I recall being NVIDIA.

**Comment by rsxdalv** [comment]
The installer brings it's own conda, the warning probably means that the installer's conda is out of date.

Yes, A) which installs NVIDIA based drivers should be correct. However, it's likely that it's gone wrong, tbh I still don't understand why Windows 11 is magically different from Windows 10, but that is the current reality. 
The problem is probably in this setup:
```sh
conda install -y -k pytorch[version=2,build=py3.10_cuda11.7*] torchvision torchaudio pytorch-cuda=11.7 cuda-toolkit ninja git -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia
```

it's likely that with a different pytorch version/build it would work; need to find which one.

**Comment by freecoderwaifu** [comment]
Happened to me too on my first install, most likely due to install issues caused by my firewall (Tinywall). Noticed some errors due to downloads not being allowed, reran the start.bat and the update.bat and that allowed the UI to install and launch, but then I encountered that error.

Managed to fix it by activating the conda venv (easiest way for me was making a copy of `start_windows.bat`, deleting everything including and below `@rem setup installer env` and running that .bat in the Terminal) and then reinstalling torch 2 and xformers with:
```
pip install --force-reinstall torch torchvision --index-url https://download.pytorch.org/whl/cu118
pip install --force-reinstall --no-deps --pre xformers
```
That allowed all inference from bark, musicgen and tortoise to work on GPU and fixed the issue, though I didn't try training.

Then I did a clean install of the UI, deleting the folder and extracting the installer files again, to test if the torch method worked reliably, disabling the firewall entirely during install. This time there were no errors and there was no need to reinstall torch, everything worked after the install. 

So definitely an issue during the components downloading and installing, in my case caused by the firewall not allowing downloads on time.  

Using Windows 11, CUDA 12.1, Python 3.10.11, one driver before the latest Nvidia driver.

**Comment by mweldon** [comment]
I'm running Windows 10 and I have the same issue.

**Comment by rsxdalv** [comment]
> When I launch I get this message:
> 
> ```
> No GPU being used. Careful, inference might be very slow!
> ```
> 
> I also get this message earlier in the log, though I am not sure it is related:
> 
> ```
> WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
>     PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
>     Python  3.10.11 (you have 3.10.11)
>   Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
>   Memory-efficient attention, SwiGLU, sparse and more won't be available.
>   Set XFORMERS_MORE_DETAILS=1 for more details
> ```
> 
> I indicated option "A" when I installed but it didn't seem to get my 4090 GPU. Should I try reinstalling, or is there any quicker way to try to repair the GPU detection issue?

I just looked at it again and for context, it seems most likely that it has installed the wrong dependencies. The installer installs pytorch + cuda 11.7.0, as seen here:
`conda install -y -k pytorch[version=2,build=py3.10_cuda11.7*] torchvision torchaudio pytorch-cuda=11.7 cuda-toolkit ninja git -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia`

So if you ever see a PyTorch 2.0.1+cpu, that means that the problem already starts with pytorch.

**Comment by rsxdalv** [comment]
> Happened to me too on my first install, most likely due to install issues caused by my firewall (Tinywall). Noticed some errors due to downloads not being allowed, reran the start.bat and the update.bat and that allowed the UI to install and launch, but then I encountered that error.
> 
> Managed to fix it by activating the conda venv (easiest way for me was making a copy of `start_windows.bat`, deleting everything including and below `@rem setup installer env` and running that .bat in the Terminal) and then reinstalling torch 2 and xformers with:
> 
> ```
> pip install --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> pip install --force-reinstall --no-deps --pre xformers
> ```
> 
> That allowed all inference from bark, musicgen and tortoise to work on GPU and fixed the issue, though I didn't try training.
> 
> Then I did a clean install of the UI, deleting the folder and extracting the installer files again, to test if the torch method worked reliably, disabling the firewall entirely during install. This time there were no errors and there was no need to reinstall torch, everything worked after the install.
> 
> So definitely an issue during the components downloading and installing, in my case caused by the firewall not allowing downloads on time.
> 
> Using Windows 11, CUDA 12.1, Python 3.10.11, one driver before the latest Nvidia driver.

Great job! By the way, if you just want to run some commands in the activated conda environment, you can open cmd_windows.bat and you'll have the pip there.

**Comment by MiYakuGaming** [comment]
Nothing here I used works, is there any way to use GPU on Tortoise?

**Comment by rsxdalv** [comment]
> Nothing here I used works, is there any way to use GPU, on Windows 10 using NVIDIA GeForce RTX, on Tortoise?

Yes, Windows 10 with CUDA should work, also with tortoise

**Comment by MiYakuGaming** [comment]
> > Nothing here I used works, is there any way to use GPU, on Windows 10 using NVIDIA GeForce RTX, on Tortoise?
> 
> Yes, Windows 10 with CUDA should work, also with tortoise

How do I make that happen?
I can get Tortoise to work for once but it won't use Cuda nor my GPU and it's very slow:
UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')

I have installed Cuda many times and it's still saying this, any suggestions?

**Comment by rsxdalv** [comment]
> > > Nothing here I used works, is there any way to use GPU, on Windows 10 using NVIDIA GeForce RTX, on Tortoise?
> > 
> > 
> > Yes, Windows 10 with CUDA should work, also with tortoise
> 
> How do I make that happen? I can get Tortoise to work for once but it won't use Cuda nor my GPU and it's very slow: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling warnings.warn('User provided device_type of 'cuda', but CUDA is not available. Disabling')
> 
> I have installed Cuda many times and it's still saying this, any suggestions?

Do the other webui's install correctly with GPU? I'm thinking that it's a problem with the torch installation. I can just suggest reinstalling torch using this conda command (must be run with cmd_windows.bat):

`conda install -y -k pytorch[version=2,build=py3.10_cuda11.7*] torchvision torchaudio pytorch-cuda=11.7 cuda-toolkit ninja git -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia`

But I feel like you might have already done it.

In that case, to debug we can do these:

within cmd_windows (anaconda environment):

```
pip show pytorch
pip show torchaudio
```

I would like to see if these are appropriate and don't contain "cpu" in their names. To be honest I don't remember if installing CUDA separately is even a requirement anymore, since I have installed *all* of them.

Just for reference, this project uses Cuda 11.7

**Comment by MiYakuGaming** [comment]
Never mind, I wasn't aware there was a new installer download, I followed the instructions and I don't get the CUDA error anymore, thanks!

**Comment by rsxdalv** [comment]
It seems that this issue might have been resolved, so I will close it for now.

**Comment by rsxdalv** [comment]
https://github.com/rsxdalv/tts-generation-webui/pull/126

At some point in time xformers 0.0.20 became the default, causing a torch 2.0.1 installation that breaks _everything_. This issue should be resolved now. Apologies to all the new users who got affected by this.

What's more unfortunate is that audiocraft, which started this issue, can use torch 2.0.0 and 2.0.1 so it can't be "fixed" there. Expect thousands of users across different projects destroying their pytorch installations..

**Comment by yo1nkers** [comment]
The latest update did not work for me. Will I be running an update, or will I be doing git pull? Or should I just perform another clean install.

**Comment by rsxdalv** [comment]
update_windows.bat

**Comment by yo1nkers** [comment]
The issue is still present. Your update may've presented further fixes for everyone but it appears not for me.

Will have to perhaps overlook the code and see if I can come up with a resolution

**Comment by rsxdalv** [comment]
I'm sorry, I misunderstood. Normally you update using update_windows.bat but if we were still talking about the wrong torch being installed, then (assuming it would work, since we have had so many issues, and thank you for your patience and corporation) it would require a clean install. Other techniques might fail.

I got this issue mixed up with Tortoise problems.

**Comment by yo1nkers** [comment]
> I'm sorry, I misunderstood. Normally you update using update_windows.bat but if we were still talking about the wrong torch being installed, then (assuming it would work, since we have had so many issues, and thank you for your patience and corporation) it would require a clean install. Other techniques might fail.
> 
> I got this issue mixed up with Tortoise problems.

It is with over-resounding happiness I have to state the issue has been resolved for me upon doing a clean install.

I'm happy for the issue to be closed as solved.
